config/routes.rb
Rails.application.routes.draw do
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
  get 'work', to: 'work_experience#work'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
	  	:to => "abhidec1990@gmail.com",
	  	:from => %("#{name}" <#{email}>)
    }
  end

end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to @post, notice: "Article was successfully saved!!"
      else
        render 'new', notice: "Unable to save !! Don't know why :("
      end
    end

    def show
    end

    def edit
    end

    def update
      if @post.update(post_params)
        redirect_to @post, notice: "Article successfully updated!!"
      else
        render 'edit', notice: "Unable to update :("
      end
    end


  def destroy
    @post.destroy
    redirect_to posts_path
  end

    private

    def post_params
      params.require(:post).permit(:title, :content, :slug)
    end

    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: "Project was successfully saved!!"
    else
      render 'new', notice: "Unable to save !! Don't know why :("
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Project successfully updated!!"
    else
      render 'edit', notice: "Unable to update :("
    end
  end


def destroy
  @project.destroy
  redirect_to projects_path
end

  private

  def project_params
    params.require(:project).permit(:title, :description, :link, :time_period, :slug)
  end

  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
  @projects = Project.all.limit(4).order("created_at desc")
end

end

app/controllers/work_experience_controller.rb
class WorkExperienceController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true, link_attributes: { target: '_blank' })
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_experience_helper.rb
module WorkExperienceHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for your message!</h1>
	<p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>
<p id="page_title2">You can also contact me on my email address: <strong>abhidec1990@gmail.com</strong></p>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name %><br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>

		<br>

		<%= f.label :message %><br>
		<%= f.text_area :message, as: :text %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div>

		<%= f.submit 'Send Message', class: "button" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suvajit Chakrabarty - Full Stack and Software Developer</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <script src="https://use.fontawesome.com/b7a587aa34.js"></script>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="main_navigation" class ="clearfix">
      <%= link_to "Suvajit Chakrabarty", root_path, class: "name" %>
      <nav>
        <%= link_to "Professional Experience", work_path %>
        <%= link_to "Projects", projects_path %>
        <%= link_to "Blog", posts_path %>
        <%= link_to "Contact", new_contact_path %>
      </nav>
    </header>
    <%= yield %>
    <footer id="main_footer">
      <p class="copyright">&copy;2017 Suvajit Chakrabarty</p>
      <nav>
        <a href="https://www.linkedin.com/in/suvajit-chakrabarty/" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
        <a href="https://github.com/esjayrockz" target="_blank"><i class="fa fa-github" aria-hidden="true"></i></a>
        <a href="https://twitter.com/esjayrockz" target="_blank"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
    </nav>

    </footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = '<%= url_for(post_url(@post)) %>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.title = '<%= @post.title %>';
};



(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://suvajit-com.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "count") %> prevented this post from saving:</h2>
  <ul>
    <%= @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <br>
  <br>

  <%= f.label :content,"Enter content" %><br>
  <%= f.text_area :content %>
  <br>
  <br>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>Edit Blog article</h1>
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">My Blog</h1>
<div id="posts_wrapper" class="skinny_wrapper">
  <% @posts.each do |post| %>
<div class="post">
  <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
  <h2><a href="#"><%= link_to post.title, post %></a></h2>
  <hr>
</div>
  <% end %>



  <%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Blog article</h1>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%=@post.created_at.strftime('%A, %B %d')%></p>
    <h1><%=@post.title%></h1>
    <hr>
  </header>

  <div id="content">

<%= markdown @post.content%>

  </div>
  <div id="disqus_margin">
  <%= render 'disqus' %>
  </div>
</div>


<br>
<br>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <h2><%= pluralize(@project.errors.count, "count") %> prevented this project from saving:</h2>
  <ul>
    <%= @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <br>
  <br>

  <%= f.label :description,"Enter description" %><br>
  <%= f.text_area :description %>
  <br>
  <br>

  <%= f.label :link,"Enter link" %><br>
  <%= f.text_field :link %>
  <br>
  <br>

  <%= f.label :time_period,"Enter time period of Project" %><br>
  <%= f.text_field :time_period %>
  <br>
  <br>

  <%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>Edit Project</h1>
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Projects</h1>
<div id="posts_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
<div class="post">
  <p class="date"><%= project.time_period %></p>
  <h2><a href="#"><%= link_to project.title, project %></a></h2>
  <hr>
</div>
  <% end %>



<%= will_paginate @projects %>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New Project</h1>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%=@project.created_at.strftime('%A, %B %d')%></p>
    <h1><%=@project.title%></h1>
    <hr>
  </header>
  <div id="content">

    <%= markdown @project.description%>
    <% if !@project.link.blank?%>
      <div class="button_wrapper">
      <a href = "<%= @project.link %>" class= "project_button" target="_blank">Visit link </a>
      </div>
    <% end %>


  </div>
  <hr>
  <%= @project.time_period %>

</div>


<br>
<br>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="col-1 about homepage_content">
    <h2>About</h2>
    <hr>
    <p>I'm currently a Full Stack Web Developer Intern at an Education Coaching Center(Ramana Coaching Center) and a Computer Science Graduate Student at UNC Charlotte.</p>
    <p>I love developing software applications using Javascript, Node.JS, React.JS, Redux, Angular.JS, Ruby on Rails and many other technologies.</p>
    <p>Some of the other web technologies that I have worked with are:
      <ul>
        <li><strong>Databases:</strong> MongoDB, Firebase, Oracle, MS SQL Server 2008/2012, Netezza, MySQL.</li>
        <li><strong>Web technologies:</strong> Redux, Redux Thunk Middleware, JavaScript ES6, Socket.IO, AWS, EC2, Heroku, REST APIs, Babel, Webpack, JSX, jQuery, Axios, Ajax(XHR & Fetch), Mongoose, Firebase Authentication, JWTs, Hashing, Git/Github, Unix, Templating- (Mustache.JS, Handlebars), Bootstrap, SCSS, SASS, NPM, Yarn, JSON.</li>
        <li><strong>Testing Tools:</strong> Jest, Enzyme, Snapshot Testing, Mocha, SuperTest, Jasmine.</li>
      </ul>
    </p>
<p> I have 3 years of prior work experience as a SQL Developer.</p>
  </div>
  <div class="col-2 homepage_content">
  <h2><%= link_to "Professional Experience", work_path %></h2>
  <hr>
  <h3><strong>Full Stack Developer Intern - Ramana Coaching Center, Charlotte, USA</strong></h3>
  <p class="date"> May 2018 - Present</p>
  <h3>
    <ul>
      <li>Full Stack Developer Intern in Education Portal Web Application used simultaneously by up to 300 users.</li>
      <li>Led team of interns in the development of Front end layer of Application using AngularJS (v1.x), Bootstrap, CSS, HTML.</li>
      <li>Migrate existing JavaScript and jQuery code to AngularJS (v1.x) and implement new functionality using AngularJS.</li>
      <li>Design Dashboards in Web Application using Bootstrap and CSS and responsible for making it mobile responsive.</li>
      <li>Involved in multi-tiered Java EE using Spring MVC Model connecting to MySQL Database.</li>
      <li>Implement Spring MVC Controllers, Services, DAO and DTO design patterns.</li>
    </ul>
  </h3>
  <h3><%= link_to "View full work experience...", work_path %></h3>
  </div>
  <div class="col-3 homepage_content">
    <h2><%= link_to "Projects", projects_path %></h2>
    <hr>
    <% @projects.each do |project| %>
    <h3><%= link_to project.title, project%></h3>
    <p class="date"> <%= project.time_period %></p>
    <% end %>
    <h3><%= link_to "View more...", projects_path %></h3>
  </div>
</div>

app/views/work_experience/work.html.erb
<h1 id="page_title">Work Experience</h1>
<div id="posts_wrapper" class="skinny_wrapper">
  <div class="post">
    <p class="date">May 2016 - November 2016</p>
    <h2>Full Stack Developer Intern - Ramana Coaching Center, Charlotte, USA</h2>
    <p class="tasks">
    <ul>
      <li>Full Stack Developer Intern in Education Portal Web Application used simultaneously by up to 300 users.</li>
      <li>Led team of interns in the development of Front end layer of Application using AngularJS (v1.x), Bootstrap, CSS, HTML.</li>
      <li>Migrate existing JavaScript and jQuery code to AngularJS (v1.x) and implement new functionality using AngularJS.</li>
      <li>Design Dashboards in Web Application using Bootstrap and CSS and responsible for making it mobile responsive.</li>
      <li>Involved in multi-tiered Java EE using Spring MVC Model connecting to MySQL Database.</li>
      <li>Implement Spring MVC Controllers, Services, DAO and DTO design patterns.</li>
    </ul>
</p>
    <hr>
  </div>
  <div class="post">
    <p class="date">January 2014 - November 2016</p>
    <h2>SQL Developer - Cognizant Technology Solutions, Kolkata, India</h2>
    <p class="tasks">
    <ul>
      <li>SQL Developer in Data Warehousing Projects, ETL and Business Intelligence projects for various clients: Fossil, Sodexo, Kantar, Lululemon, Realogy and 7-Eleven.</li>
      <li>Worked with various Relational Databases like Oracle, MS SQL Server, Netezza and DB2 with tables containing more than 1 Billion records and validated data in various stages of Data Warehouse using complex SQL/PL-SQL Scripts.</li>
      <li>Worked with Stakeholders following the Agile Scrum Software Development Process.</li>
    </ul>

    </p>
    <hr>
  </div>
  <!-- <div class="post">
    <p class="date">June 2015 - January 2016</p>
    <h2>Quality Analyst in Data Migration and Reporting Project for Fossil, USA based Client</h2>
    <p class="tasks">¬	Performed End to End system testing and developed SQL scripts in Netezza Database with tables containing more than 500 million records.<br>
¬	Wrote UNIX/Linux Shell commands for purpose of QA.<br>
¬	Performed testing and validation of Reports using SQL Scripts.<br>
¬	Used Intuit Quick Base Project management tool for maintaining log of project activities.

</p>
    <hr>
  </div>
<div class="post">
  <p class="date">December 2014 - May 2015</p>
  <h2>Quality Analyst in ETL and Data Migration Project for Kantar, UK based Client</h2>
  <p class="tasks">¬	Performed quality assurance in parallel databases (Oracle and MS SQL Server) simultaneously to assure data synchronization.<br>
¬	Wrote SQL Scripts and performed End to End system testing, Incremental testing & Regression testing.<br>
¬	Developed Microsoft SSIS ETL packages to establish data transfer process from Oracle(source) to MS SQL Server Database(target) for Quality Analysis.<br>
¬	Executed Retrofit testing in Front flow data migration to ensure lack of anomalies in data updated directly in the Target System.<br>
¬	Executed Backflow testing to ensure source and target have correct data synced with each other.

</p>
  <hr>
</div>
<div class="post">
  <p class="date">November 2014</p>
  <h2>OBIEE Reporting Analyst in OBIEE Reporting Project for Sodexo, France based Client</h2>
  <p class="tasks">¬	Performed Testing of OBIEE Reports using SQL Scripts.<br>
¬	Performed End to End system testing.<br>
¬	Prepared Test Scenarios and Test Case Design.<br>
¬	Created and executed test cases.<br>
¬	Created regression suit and Test data Preparation.<br>

</p>
  <hr>
</div>
<div class="post">
  <p class="date">September 2014 - October 2014</p>
  <h2>Reporting Analyst in Crystal Reports for 7-Eleven, USA based Client</h2>
  <p class="tasks">¬	Created Test Strategy and Plan.<br>
¬	Analyzed and validated Crystal reports using SQL queries and procedures.<br>
¬	Used HP Quality Center to log defects.

</p>
  <hr>
</div> -->
</div>